version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update the VARIANT arg to pick a Java version: up tp 17
        VARIANT: "17"
        # Options
        INSTALL_MAVEN: "false"
        INSTALL_GRADLE: "true"
        INSTALL_NODE: "true"
        NODE_VERSION: "14"
    ports:
      - 8081:8081
      - 3000:3000
    volumes:
      - ..:/sample_java_node:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    depends_on:
      - db

  db:
    image: mysql:8.0.25
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --skip-character-set-client-handshake
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sample_java_node
      MYSQL_PASSWORD: sample_java_node
      MYSQL_DATABASE: sample_java_node
      TZ: "Asia/Tokyo"
